name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'master')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}

      - name: Add cPanel to known_hosts
        run: |
          ssh-keyscan -p 45022 developermakmurjaya.my.id >> ~/.ssh/known_hosts

      - name: Fetch complete history
        run: git fetch --unshallow

      - name: Push to cPanel
        run: |
          git remote add cpanel ssh://develo12@developermakmurjaya.my.id:45022/home/develo12/public_html/
          git push -u cpanel master --force